### ISSUE TITLE
RSS feeds per sustainability topic

### ISSUE THREAD

**Issue by jamstooks** [AASHE/sustainable-campus-partners-directory#15]
@baronvonvaderham - could you add RSS feeds for each sustainability category? Bob did something like this in the bulletin that you could reference.

We'll be integrating this feed into the hub.

**Comment by baronvonvaderham** [comment]
Added in commit 73d09d238c55f45aa9651cecf12685db9aaaa454

Need to decide what to use for titles and descriptions, currently just inserted placeholder strings.
