### ISSUE TITLE
Discount Integration

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/sustainable-campus-partners-directory#23]
Add a system for submitting and displaying discounts offered by business members to move this functionality away from the Drupal site.

**Comment by rerb** [comment]
Hi, Scott.  Don't know if this is still relevant -- your call.

**Comment by baronvonvaderham** [comment]
I don't think so. It hasn't been talked about since (14 months) and we're going to eventually abandon this to instead integrate it with the new site.
